### PR TITLE
Generate and upload AppImage for each git push

### PR DESCRIPTION
**Pull request by probonopd**
As requested by @Symbian9 this PR, when merged, will compile this application on [Travis CI](https://travis-ci.org/) upon each `git push`, and upload an [AppImage](http://appimage.org/) to your GitHub Releases page.

Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Applications packaged as an AppImage can run on many distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs
- Can use the same AppImages when dual-booting multiple distributions
- Can be listed in the [AppImageHub](https://appimage.github.io/apps) central directory of available AppImages
- Can double as a self-extracting compressed archive with the `--appimage-extract` parameter

[Here is an overview](https://appimage.github.io/apps) of projects that are already distributing upstream-provided, official AppImages.

__PLEASE NOTE:__ For this to work, you need to enable Travis CI for your repository as [described here](https://travis-ci.org/getting_started) __prior to merging this__, if you haven't already done so. Also, You need to set up `GITHUB_TOKEN` in Travis CI for this to work; please see https://github.com/probonopd/uploadtool.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

### CODE REVIEW

**Comment by probonopd** [comment]
Test AppImage is available at https://github.com/probonopd/SteamCAD/releases.

Please note that I had to use some really ugly hackery to work around the non-existing
* `make install` (it's the standard)
* icon (I have used a placeholder)
* desktop file (I have made one)
* Code (in the application) that populates `$HOME/SteamCAD` properly

resulting in quite a mess. These things should be done properly.

**Comment by oskardolch** [comment]
Hi, I appreciate your work on this. I have merged your changes into master. Regarding the "make install", I am not sure how much effort it would require. I am afraid it would need to employ the automake and autoconf and other stuff I am not familiar with. So I have neither skills no resource to do it myself, but again, any contribution of this kind would be welcome.
Regarding the suggestion that the software should check for the ini files and copy them if missing, this is certainly a good idea, however it is tied with the existence of "make install", since the files should first be copied from the installation location to a common location (/usr/local/share ??? I am not sure), so that the software can find it there and copy them to the user SteamCAD config folder if appropriate. So there is nothing to add to the code until we have a working "make install" version.

**Comment by probonopd** [comment]
Thanks for merging 👍 

You are almost there:

Currently`GITHUB_TOKEN` missing, please set it in the Travis CI settings of this project.
https://travis-ci.org/oskardolch/SteamCAD/jobs/456562587#L819

To fix this:

 - On https://github.com/settings/tokens, click on "Generate new token" and generate a token with at least the `public_repo`, `repo:status`, and `repo_deployment` scopes
 - On Travis CI, go to the settings of your project at `https://travis-ci.org/oskardolch/SteamCAD/settings`
 - Under "Environment Variables", add key `GITHUB_TOKEN` and the token you generated above as the value. **Make sure that "Display value in build log" is set to "OFF"!**

If you add a corrent `GITHUB_TOKEN`  to the project settings in Travis CI, then your builds will automatically be uploaded to https://github.com/oskardolch/SteamCAD/releases.

More information:
https://github.com/probonopd/uploadtool

**Comment by ghost** [comment]
> Test AppImage is available at

Thanks, @probonopd & @oskardolch ! ;-)

I just updated my repo too, so latest AppImage also available at:

- https://github.com/Symbian9/SteamCAD/releases/tag/continuous

Think, later need setup Windows builds via `.travis.yml`. 

P.S.: Also need move Windows binary (`SteamCADbinWin32.zip`,	`SteamCADbinWin64.zip`) and PDF (`SteamCAD.pdf`) from `master` sources to "Releases" section as "Assets".

- https://github.com/oskardolch/SteamCAD/issues/4

**Comment by ghost** [comment]
> - icon (I have used a placeholder)
> - desktop file (I have made one)

I started collect general feature request here as TODO list:

- https://github.com/oskardolch/SteamCAD/issues/3

If need, I would be happy to help with icon design.

**Pull request merged**
